import { YEAR8_WORDS } from "./year8-vocab";
import { YEAR9_WORDS } from "./year9-vocab";
import { YEAR9_MORE_ABLE_WORDS } from "./year9-more-able-vocab";

export type Difficulty = "Low" | "Medium" | "High";

export type Word = {
  id: string;
  year: string;
  term: string;
  topic: string;
  difficulty: Difficulty;
  french: string;
  english: string;
  image?: string;
};

let counter = 0;
const w = (
  year: string,
  term: string,
  topic: string,
  difficulty: Difficulty,
  french: string,
  english: string,
  image?: string,
): Word => ({
  id: `w${++counter}`,
  year,
  term,
  topic,
  difficulty,
  french,
  english,
  ...(image ? { image } : {}),
});

export const YEARS = ["Year 7", "Year 8", "Year 9 Mixed Ability", "Year 9 More Able"];
export const TERMS = ["Term 1", "Term 2", "Term 3", "Term 4", "Term 5", "Term 6"];
export const TOPICS = [
  "A day at school",
  "Adjectives",
  "Animals",
  "At the canteen",
  "Colours",
  "Days of the week",
  "Family",
  "Future tense",
  "Greetings",
  "Infinitives",
  "Likes and dislikes",
  "Months",
  "Numbers",
  "Opinions and reasons",
  "Opinions on catacombs",
  "Personality",
  "Physical description",
  "Physical description recap",
  "Adverbs of frequency",
  "Different holidays",
  "Film genres",
  "Film opinions",
  "Holidays",
  "In Paris past tense",
  "Irregular past tense",
  "Monuments of Paris",
  "Music",
  "Relationships",
  "Seasons",
  "Sport",
  "Together we",
  "Weather",
  "School subjects",
  "The time",
  "The uniform",
  "Identity",
  "Opinions",
  "School life",
  "Christmas",
  "Celebrations",
  "Past tense",
  "At the restaurant",
  "Leisure",
  "Fashion",
];
export const DIFFICULTIES: Difficulty[] = ["Low", "Medium", "High"];

export const SEED_WORDS: Word[] = [
  // Year 7 — Term 1 — Greetings
  w("Year 7", "Term 1", "Greetings", "Medium", "Bonjour", "Good morning/hello"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Salut", "Hi / bye"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Coucou", "Hiya"),
  w("Year 7", "Term 1", "Greetings", "Medium", "A plus", "See you"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Au revoir", "Good bye"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Comment tu t'appelles?", "What is your name?"),
  w("Year 7", "Term 1", "Greetings", "Low", "Je m'appelle …", "My name is …"),
  w("Year 7", "Term 1", "Greetings", "Low", "ça va ?", "How are you?"),
  w("Year 7", "Term 1", "Greetings", "Low", "ça va (très) bien", "I am (very) good"),
  w("Year 7", "Term 1", "Greetings", "Medium", "ca va super", "I feel super"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Non, ça va mal", "No, I feel bad"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Non, ça ne va pas !", "No, I am not good"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Comme ci comme ça", "so so"),
  w("Year 7", "Term 1", "Greetings", "Medium", "pas mal", "not bad"),
  w("Year 7", "Term 1", "Greetings", "Medium", "Quel âge as-tu?", "How old are you?"),
  w("Year 7", "Term 1", "Greetings", "Low", "J'ai … ans", "I have … years of age"),
  w(
    "Year 7",
    "Term 1",
    "Greetings",
    "Medium",
    "Quelle est la date de ton anniversaire?",
    "When is your birthday?",
  ),
  w(
    "Year 7",
    "Term 1",
    "Greetings",
    "Low",
    "Mon anniversaire c'est le ……",
    "My birthday is on the …",
  ),
  w("Year 7", "Term 1", "Greetings", "Medium", "premier", "first"),

  // Year 7 — Term 1 — Numbers
  w("Year 7", "Term 1", "Numbers", "Low", "un", "one"),
  w("Year 7", "Term 1", "Numbers", "Low", "deux", "two"),
  w("Year 7", "Term 1", "Numbers", "Low", "trois", "three"),
  w("Year 7", "Term 1", "Numbers", "Low", "quatre", "four"),
  w("Year 7", "Term 1", "Numbers", "Low", "cinq", "five"),
  w("Year 7", "Term 1", "Numbers", "Low", "six", "six"),
  w("Year 7", "Term 1", "Numbers", "Low", "sept", "seven"),
  w("Year 7", "Term 1", "Numbers", "Low", "huit", "eight"),
  w("Year 7", "Term 1", "Numbers", "Low", "neuf", "nine"),
  w("Year 7", "Term 1", "Numbers", "Low", "dix", "ten"),
  w("Year 7", "Term 1", "Numbers", "Low", "onze", "eleven"),
  w("Year 7", "Term 1", "Numbers", "Low", "douze", "twelve"),
  w("Year 7", "Term 1", "Numbers", "Low", "treize", "thirteen"),
  w("Year 7", "Term 1", "Numbers", "Low", "quatorze", "fourteen"),
  w("Year 7", "Term 1", "Numbers", "Low", "quinze", "fifteen"),
  w("Year 7", "Term 1", "Numbers", "Low", "seize", "sixteen"),
  w("Year 7", "Term 1", "Numbers", "Low", "dix-sept", "seventeen"),
  w("Year 7", "Term 1", "Numbers", "Low", "dix-huit", "eighteen"),
  w("Year 7", "Term 1", "Numbers", "Low", "dix-neuf", "nineteen"),
  w("Year 7", "Term 1", "Numbers", "Low", "vingt", "twenty"),
  w("Year 7", "Term 1", "Numbers", "Low", "vingt-et-un", "twenty-one"),
  w("Year 7", "Term 1", "Numbers", "Low", "vingt-deux", "twenty-two"),
  w("Year 7", "Term 1", "Numbers", "Low", "vingt-trois", "twenty-three"),
  w("Year 7", "Term 1", "Numbers", "Low", "vingt-quatre", "twenty-four"),
  w("Year 7", "Term 1", "Numbers", "Low", "trente", "thirty"),
  w("Year 7", "Term 1", "Numbers", "Low", "trente-et-un", "thirty-one"),

  // Year 7 — Term 1 — Days of the week
  w("Year 7", "Term 1", "Days of the week", "Medium", "lundi", "Monday"),
  w("Year 7", "Term 1", "Days of the week", "Medium", "mardi", "Tuesday"),
  w("Year 7", "Term 1", "Days of the week", "Medium", "mercredi", "Wednesday"),
  w("Year 7", "Term 1", "Days of the week", "Medium", "jeudi", "Thursday"),
  w("Year 7", "Term 1", "Days of the week", "Low", "vendredi", "Friday"),
  w("Year 7", "Term 1", "Days of the week", "Low", "samedi", "Saturday"),
  w("Year 7", "Term 1", "Days of the week", "Low", "dimanche", "Sunday"),

  // Year 7 — Term 1 — Months
  w("Year 7", "Term 1", "Months", "Medium", "janvier", "January"),
  w("Year 7", "Term 1", "Months", "Medium", "février", "February"),
  w("Year 7", "Term 1", "Months", "Medium", "mars", "March"),
  w("Year 7", "Term 1", "Months", "Medium", "avril", "April"),
  w("Year 7", "Term 1", "Months", "Medium", "mai", "May"),
  w("Year 7", "Term 1", "Months", "Medium", "juin", "June"),
  w("Year 7", "Term 1", "Months", "Low", "juillet", "July"),
  w("Year 7", "Term 1", "Months", "Low", "août", "August"),
  w("Year 7", "Term 1", "Months", "Low", "septembre", "September"),
  w("Year 7", "Term 1", "Months", "Low", "octobre", "October"),
  w("Year 7", "Term 1", "Months", "Low", "novembre", "November"),
  w("Year 7", "Term 1", "Months", "Low", "décembre", "December"),

  // Year 7 — Term 2 — Colours
  w("Year 7", "Term 2", "Colours", "Low", "bleu", "blue"),
  w("Year 7", "Term 2", "Colours", "Low", "rouge", "red"),
  w("Year 7", "Term 2", "Colours", "Low", "vert", "green"),
  w("Year 7", "Term 2", "Colours", "Low", "jaune", "yellow"),
  w("Year 7", "Term 2", "Colours", "Low", "noir", "black"),
  w("Year 7", "Term 2", "Colours", "Low", "blanc", "white"),
  w("Year 7", "Term 2", "Colours", "Medium", "blanche", "white (feminine)"),
  w("Year 7", "Term 2", "Colours", "Low", "violet", "purple"),
  w("Year 7", "Term 2", "Colours", "Low", "rose", "pink"),
  w("Year 7", "Term 2", "Colours", "Low", "orange", "orange"),
  w("Year 7", "Term 2", "Colours", "Low", "marron", "brown"),
  w("Year 7", "Term 2", "Colours", "Low", "gris", "grey"),

  // Year 7 — Term 2 — Adjectives
  w("Year 7", "Term 2", "Adjectives", "Low", "petit", "small"),
  w("Year 7", "Term 2", "Adjectives", "Low", "grand", "big (as tall)"),
  w(
    "Year 7",
    "Term 2",
    "Adjectives",
    "Medium",
    "ex: J'ai un petit chien noir",
    "I have a small black dog",
  ),

  // Year 7 — Term 2 — Animals
  w("Year 7", "Term 2", "Animals", "Medium", "J'ai", "I have"),
  w("Year 7", "Term 2", "Animals", "Medium", "Je n'ai pas de", "I don't have any"),
  w("Year 7", "Term 2", "Animals", "Medium", "Je n'ai pas d'animal", "I do not have any animals"),
  w("Year 7", "Term 2", "Animals", "Low", "un chien", "a dog"),
  w("Year 7", "Term 2", "Animals", "Low", "un chat", "a cat"),
  w("Year 7", "Term 2", "Animals", "Low", "un cheval", "a horse"),
  w("Year 7", "Term 2", "Animals", "Low", "un lapin", "a rabbit"),
  w("Year 7", "Term 2", "Animals", "Low", "un poisson", "a fish"),
  w("Year 7", "Term 2", "Animals", "Medium", "un oiseau", "a bird"),
  w("Year 7", "Term 2", "Animals", "Medium", "un serpent", "a snake"),
  w("Year 7", "Term 2", "Animals", "Medium", "un hamster", "a hamster"),
  w("Year 7", "Term 2", "Animals", "Medium", "une souris", "a mouse"),
  w("Year 7", "Term 2", "Animals", "Medium", "une tortue", "a tortoise"),

  // Year 7 — Term 2 — Family
  w("Year 7", "Term 2", "Family", "Medium", "dans ma famille", "in my family"),
  w("Year 7", "Term 2", "Family", "Medium", "il y a …", "there is/are …"),
  w("Year 7", "Term 2", "Family", "Low", "mon père", "my father"),
  w("Year 7", "Term 2", "Family", "Low", "ma mère", "my mother"),
  w("Year 7", "Term 2", "Family", "Low", "mon frère", "my brother"),
  w("Year 7", "Term 2", "Family", "Low", "ma sœur", "my sister"),
  w("Year 7", "Term 2", "Family", "Medium", "mon grand-père", "my grandfather"),
  w("Year 7", "Term 2", "Family", "Medium", "ma grand-mère", "my grandmother"),
  w("Year 7", "Term 2", "Family", "High", "mon beau-père", "my stepfather"),
  w("Year 7", "Term 2", "Family", "High", "ma belle-mère", "my stepmother"),
  w("Year 7", "Term 2", "Family", "Medium", "mon demi-frère", "my step/half-brother"),
  w("Year 7", "Term 2", "Family", "Medium", "ma demi-sœur", "my step/half sister"),
  w("Year 7", "Term 2", "Family", "Medium", "Mon père s'appelle …", "my father is called …"),
  w(
    "Year 7",
    "Term 2",
    "Family",
    "High",
    "j'ai un frère qui s'appelle …",
    "I have a brother who is called …",
  ),
  w("Year 7", "Term 2", "Family", "High", "Mes soeurs s'appellent …", "my sisters … are called …"),
  w("Year 7", "Term 2", "Family", "High", "il/elle a … ans", "he/she has … years of age"),

  // Year 7 — Term 3 — Likes and dislikes
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "J'aime", "I like"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "J'adore", "I love"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "Je n'aime pas", "I don't like"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "Je déteste", "I hate"),
  w("Year 7", "Term 3", "Likes and dislikes", "High", "je préfère", "I prefer"),
  w("Year 7", "Term 3", "Likes and dislikes", "Low", "c'est génial", "it's great"),
  w("Year 7", "Term 3", "Likes and dislikes", "Low", "c'est bien", "it's good"),
  w("Year 7", "Term 3", "Likes and dislikes", "Low", "c'est cool", "it's cool"),
  w("Year 7", "Term 3", "Likes and dislikes", "Low", "c'est ennuyeux", "it's boring"),
  w("Year 7", "Term 3", "Likes and dislikes", "Low", "c'est nul", "it's rubbish"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "les spaghettis", "spaghetti"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "l'injustice", "injustice"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "les voyages", "trips / travel"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "le rap", "rap"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "le rugby", "rugby"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "le cinéma", "cinema"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "la pizza", "pizza"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "le racisme", "racism"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "le chocolat", "chocolate"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "la danse", "dance"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "le foot (le football)", "football"),
  w("Year 7", "Term 3", "Likes and dislikes", "Medium", "les reptiles", "reptiles"),

  // Year 7 — Term 3 — Personality
  w("Year 7", "Term 3", "Personality", "Medium", "Je suis", "I am"),
  w("Year 7", "Term 3", "Personality", "Medium", "Je ne suis pas", "I am not"),
  w("Year 7", "Term 3", "Personality", "High", "Il est", "He is"),
  w("Year 7", "Term 3", "Personality", "High", "Elle est", "She is"),
  w("Year 7", "Term 3", "Personality", "High", "on dit que", "people say that"),
  w("Year 7", "Term 3", "Personality", "High", "ma mère dit que", "my mother says that"),
  w("Year 7", "Term 3", "Personality", "High", "je suis d'accord", "I agree"),
  w("Year 7", "Term 3", "Personality", "High", "je ne suis pas d'accord", "I disagree"),
  w("Year 7", "Term 3", "Personality", "Medium", "Etre", "to be"),
  w("Year 7", "Term 3", "Personality", "High", "c'est important pour moi", "it is important to me"),
  w("Year 7", "Term 3", "Personality", "Medium", "Assez", "quite"),
  w("Year 7", "Term 3", "Personality", "Medium", "Plutôt", "rather"),
  w("Year 7", "Term 3", "Personality", "Low", "Très", "very"),
  w("Year 7", "Term 3", "Personality", "Low", "branché(e)", "trendy"),
  w("Year 7", "Term 3", "Personality", "Low", "charmant(e)", "charming"),
  w("Year 7", "Term 3", "Personality", "Low", "gentil(le)", "kind"),
  w("Year 7", "Term 3", "Personality", "Low", "intelligent(e)", "intelligent"),
  w("Year 7", "Term 3", "Personality", "Low", "poli(e)", "polite"),
  w("Year 7", "Term 3", "Personality", "Low", "généreux(se)", "generous"),
  w("Year 7", "Term 3", "Personality", "Low", "curieux(se)", "curious"),
  w("Year 7", "Term 3", "Personality", "Low", "drôle", "funny"),
  w("Year 7", "Term 3", "Personality", "Low", "modeste", "modest"),
  w("Year 7", "Term 3", "Personality", "Low", "bavard", "chatty"),

  // Year 7 — Term 3 — Physical description
  w("Year 7", "Term 3", "Physical description", "Medium", "J'ai", "I have"),
  w("Year 7", "Term 3", "Physical description", "Medium", "il/elle a", "he/she has"),
  w("Year 7", "Term 3", "Physical description", "Medium", "marron", "brown"),
  w("Year 7", "Term 3", "Physical description", "Medium", "noisette", "hazel"),
  w("Year 7", "Term 3", "Physical description", "Medium", "verts", "green"),
  w("Year 7", "Term 3", "Physical description", "Medium", "bleus", "blue"),
  w("Year 7", "Term 3", "Physical description", "Medium", "blonds", "blond"),
  w("Year 7", "Term 3", "Physical description", "Medium", "châtains", "light brown"),
  w("Year 7", "Term 3", "Physical description", "Low", "bruns", "brown"),
  w("Year 7", "Term 3", "Physical description", "Medium", "blancs", "white"),
  w("Year 7", "Term 3", "Physical description", "Medium", "noirs", "black"),
  w("Year 7", "Term 3", "Physical description", "Medium", "roux", "ginger"),
  w("Year 7", "Term 3", "Physical description", "Medium", "longs", "long"),
  w("Year 7", "Term 3", "Physical description", "Medium", "mi-longs", "mid length"),
  w("Year 7", "Term 3", "Physical description", "Medium", "courts", "short"),
  w("Year 7", "Term 3", "Physical description", "Medium", "frisés", "frizzy"),
  w("Year 7", "Term 3", "Physical description", "Medium", "raides", "straight"),
  w("Year 7", "Term 3", "Physical description", "High", "bouclés", "curly"),
  w("Year 7", "Term 3", "Physical description", "Medium", "Je suis", "I am"),
  w("Year 7", "Term 3", "Physical description", "Medium", "il/elle est", "he/she is"),
  w("Year 7", "Term 3", "Physical description", "Low", "grand(e)", "tall"),
  w("Year 7", "Term 3", "Physical description", "Low", "petit(e)", "small"),
  w("Year 7", "Term 3", "Physical description", "Medium", "de taille moyenne", "of average height"),

  // Year 7 — Term 4 — School subjects
  w("Year 7", "Term 4", "School subjects", "Medium", "Le théâtre/L'art dramatique", "drama"),
  w("Year 7", "Term 4", "School subjects", "Low", "Le français", "French"),
  w("Year 7", "Term 4", "School subjects", "Medium", "La technologie", "DT"),
  w("Year 7", "Term 4", "School subjects", "Medium", "La géographie", "geography"),
  w("Year 7", "Term 4", "School subjects", "Medium", "La musique", "music"),
  w("Year 7", "Term 4", "School subjects", "Medium", "Le dessin / Les arts plastiques", "Art"),
  w("Year 7", "Term 4", "School subjects", "Medium", "L'informatique", "ICT"),
  w("Year 7", "Term 4", "School subjects", "Medium", "Le sport/L'EPS", "sport / PE"),
  w("Year 7", "Term 4", "School subjects", "Medium", "L'histoire", "history"),
  w("Year 7", "Term 4", "School subjects", "Low", "Les maths", "maths"),
  w("Year 7", "Term 4", "School subjects", "Low", "L'anglais", "English"),
  w("Year 7", "Term 4", "School subjects", "Medium", "L'espagnol", "Spanish"),
  w("Year 7", "Term 4", "School subjects", "High", "L'allemand", "German"),
  w("Year 7", "Term 4", "School subjects", "Low", "Les sciences", "sciences"),

  // Year 7 — Term 4 — Opinions and reasons
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "J'aime", "I like"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "J'adore", "I love"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "Je déteste", "I hate"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "Je n'aime pas", "I don't like"),
  w(
    "Year 7",
    "Term 4",
    "Opinions and reasons",
    "Medium",
    "Le/la prof est sympa …",
    "the teacher is nice",
  ),
  w(
    "Year 7",
    "Term 4",
    "Opinions and reasons",
    "Medium",
    "Le/la prof est sévère …",
    "the teacher is strict",
  ),
  w(
    "Year 7",
    "Term 4",
    "Opinions and reasons",
    "Medium",
    "On a beaucoup de devoirs …",
    "we have a lot of homework",
  ),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "c'est …", "it is (it's)"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "intéressant", "interesting"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "génial", "great"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "nul", "rubbish"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "facile", "easy"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "difficile", "difficult"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "drôle / marrant", "fun"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "ennuyeux/barbant", "boring"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "formidable", "amazing"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "Car / parce que", "because"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "Mais", "but"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "Aussi", "also"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "Et", "and"),
  w("Year 7", "Term 4", "Opinions and reasons", "High", "de plus", "in addition"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "assez", "quite"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "plutôt", "rather"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "très", "very"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "trop", "too (much)"),
  w("Year 7", "Term 4", "Opinions and reasons", "High", "un peu", "a bit"),
  w("Year 7", "Term 4", "Opinions and reasons", "Low", "beaucoup", "a lot"),
  w("Year 7", "Term 4", "Opinions and reasons", "Medium", "vraiment", "really"),

  // Year 7 — Term 5 — The time
  w(
    "Year 7",
    "Term 5",
    "The time",
    "Medium",
    "Il est 9 heures 10",
    "it is ten past nine (it is 9 hours 10 minutes)",
  ),
  w("Year 7", "Term 5", "The time", "Low", "9 heures", "9 o'clock"),
  w("Year 7", "Term 5", "The time", "Low", "3 heures", "3 o'clock"),
  w("Year 7", "Term 5", "The time", "Low", "Midi", "noon / midday"),
  w("Year 7", "Term 5", "The time", "Medium", "Minuit", "midnight"),
  w(
    "Year 7",
    "Term 5",
    "The time",
    "Medium",
    "Et quart",
    "quarter past (il est 9 heures et quart – 9 :15)",
  ),
  w(
    "Year 7",
    "Term 5",
    "The time",
    "Medium",
    "Et demie",
    "half-past (Il est trois heures et demie – 3 :30)",
  ),

  // Year 7 — Term 5 — A day at school
  w("Year 7", "Term 5", "A day at school", "Low", "Je commence", "I start"),
  w("Year 7", "Term 5", "A day at school", "Medium", "On commence", "we start"),
  w("Year 7", "Term 5", "A day at school", "Low", "J'étudie", "I study"),
  w("Year 7", "Term 5", "A day at school", "Medium", "On étudie", "we study"),
  w("Year 7", "Term 5", "A day at school", "Low", "Je bavarde", "I chat"),
  w("Year 7", "Term 5", "A day at school", "Medium", "On bavarde", "we chat"),
  w("Year 7", "Term 5", "A day at school", "Low", "Je rigole", "I laugh"),
  w("Year 7", "Term 5", "A day at school", "Medium", "On rigole", "we laugh"),
  w("Year 7", "Term 5", "A day at school", "Low", "Je mange", "I eat"),
  w("Year 7", "Term 5", "A day at school", "Medium", "On mange", "we eat"),
  w("Year 7", "Term 5", "A day at school", "Low", "Je parle", "I talk"),
  w("Year 7", "Term 5", "A day at school", "Medium", "On parle", "we talk"),
  w("Year 7", "Term 5", "A day at school", "High", "Je finis", "I finish"),
  w("Year 7", "Term 5", "A day at school", "High", "On finit", "we finish"),
  w(
    "Year 7",
    "Term 5",
    "A day at school",
    "Medium",
    "je ne bavarde pas en cours",
    "I do not chat in lessons",
  ),
  w(
    "Year 7",
    "Term 5",
    "A day at school",
    "Medium",
    "mon collège s'appelle …",
    "my school is called …",
  ),
  w("Year 7", "Term 5", "A day at school", "Medium", "je suis en sixième", "I am in Year 7"),
  w("Year 7", "Term 5", "A day at school", "Medium", "je suis fatigué", "I am tired"),
  w("Year 7", "Term 5", "A day at school", "Medium", "le matin", "in the morning"),
  w("Year 7", "Term 5", "A day at school", "Medium", "l'après-midi", "in the afternoon"),
  w("Year 7", "Term 5", "A day at school", "Medium", "tous les jours", "everyday"),
  w("Year 7", "Term 5", "A day at school", "Medium", "tous les …", "every …"),
  w("Year 7", "Term 5", "A day at school", "Low", "mes devoirs", "my homework"),
  w("Year 7", "Term 5", "A day at school", "Low", "les cours", "lessons"),
  w("Year 7", "Term 5", "A day at school", "Medium", "en cours", "in lesson"),
  w("Year 7", "Term 5", "A day at school", "Medium", "on a cours à …", "we have lessons at …"),
  w("Year 7", "Term 5", "A day at school", "Low", "les matières", "subjects"),
  w("Year 7", "Term 5", "A day at school", "Low", "Avec mes amis/copains", "with my friends"),
  w("Year 7", "Term 5", "A day at school", "Low", "La récré", "breaktime"),
  w("Year 7", "Term 5", "A day at school", "Medium", "à la récré", "At break time"),
  w("Year 7", "Term 5", "A day at school", "Low", "le déjeuner", "lunch time"),
  w("Year 7", "Term 5", "A day at school", "Medium", "au déjeuner", "at lunch"),
  w("Year 7", "Term 5", "A day at school", "Medium", "(à) la cantine", "(at) the canteen"),
  w("Year 7", "Term 5", "A day at school", "High", "Mon emploi du temps", "my timetable"),

  // Year 7 — Term 6 — At the canteen
  w("Year 7", "Term 6", "At the canteen", "Low", "Je mange", "I eat"),
  w(
    "Year 7",
    "Term 6",
    "At the canteen",
    "Medium",
    "À midi, je mange à la cantine",
    "At lunch/midday, I eat at the canteen",
  ),
  w("Year 7", "Term 6", "At the canteen", "Low", "du fromage", "(some) cheese"),
  w("Year 7", "Term 6", "At the canteen", "Low", "du poulet (rôti)", "(some) (roast) chicken"),
  w("Year 7", "Term 6", "At the canteen", "Medium", "du poisson", "(some) fish"),
  w("Year 7", "Term 6", "At the canteen", "Medium", "du steak haché", "(some) beef burger"),
  w("Year 7", "Term 6", "At the canteen", "Low", "du yaourt", "(some) yogurt"),
  w("Year 7", "Term 6", "At the canteen", "Low", "des crudités", "(some) raw vegetables/salad"),
  w("Year 7", "Term 6", "At the canteen", "Low", "des frites", "(some) chips"),
  w("Year 7", "Term 6", "At the canteen", "Medium", "des haricots verts", "(some) green beans"),
  w("Year 7", "Term 6", "At the canteen", "Medium", "de la pizza", "(some) pizza"),
  w(
    "Year 7",
    "Term 6",
    "At the canteen",
    "Medium",
    "de la glace à la fraise/au chocolat",
    "(some) strawberry/chocolate ice cream",
  ),
  w(
    "Year 7",
    "Term 6",
    "At the canteen",
    "Medium",
    "de la mousse au chocolat",
    "(some) chocolate mousse",
  ),
  w("Year 7", "Term 6", "At the canteen", "Medium", "de la tarte au citron", "(some) lemon tart"),
  w("Year 7", "Term 6", "At the canteen", "Medium", "de la purée", "mash"),
  w("Year 7", "Term 6", "At the canteen", "Low", "des pommes de terre", "(some) potatoes"),
  w("Year 7", "Term 6", "At the canteen", "Medium", "C'est délicieux", "it is delicious"),
  w("Year 7", "Term 6", "At the canteen", "Medium", "C'est dégoûtant", "it is disgusting"),
  w("Year 7", "Term 6", "At the canteen", "High", "Comme entrée", "as starter/for starters"),
  w("Year 7", "Term 6", "At the canteen", "High", "Comme plat", "as a main course"),
  w("Year 7", "Term 6", "At the canteen", "High", "Comme dessert", "as dessert / for dessert"),

  // Year 7 — Term 6 — The uniform
  w("Year 7", "Term 6", "The uniform", "Low", "je porte", "I wear"),
  w("Year 7", "Term 6", "The uniform", "Low", "une chemise (blanche)", "a (white) shirt"),
  w("Year 7", "Term 6", "The uniform", "Low", "un pantalon (noir)", "(black) trousers"),
  w("Year 7", "Term 6", "The uniform", "Low", "une veste (bleu marine)", "a (navy) blazer"),
  w("Year 7", "Term 6", "The uniform", "Low", "une cravate", "a tie"),
  w("Year 7", "Term 6", "The uniform", "Medium", "des chaussettes", "socks"),
  w("Year 7", "Term 6", "The uniform", "Low", "des chaussures (noires)", "(black) shoes"),
  w("Year 7", "Term 6", "The uniform", "Medium", "une jupe", "a skirt"),
  w("Year 7", "Term 6", "The uniform", "Medium", "un pull", "a sweater/a jumper"),
  w("Year 7", "Term 6", "The uniform", "Medium", "c'est pratique", "it's practical"),
  w("Year 7", "Term 6", "The uniform", "Medium", "c'est chic", "it's smart"),
  w(
    "Year 7",
    "Term 6",
    "The uniform",
    "Medium",
    "c'est facile le matin",
    "it's easy in the morning",
  ),

  // Year 7 — Term 6 — Infinitives
  w("Year 7", "Term 6", "Infinitives", "Medium", "manger", "to eat"),
  w("Year 7", "Term 6", "Infinitives", "Medium", "parler", "to talk"),
  w("Year 7", "Term 6", "Infinitives", "Medium", "rigoler", "to laugh"),
  w("Year 7", "Term 6", "Infinitives", "Medium", "bavarder", "to chat"),
  w("Year 7", "Term 6", "Infinitives", "Medium", "porter", "to wear"),
  w("Year 7", "Term 6", "Infinitives", "Medium", "j'aime porter", "I like to wear"),
  w(
    "Year 7",
    "Term 6",
    "Infinitives",
    "Medium",
    "je deteste parler",
    "I hate talking/I hate to talk",
  ),

  // Year 7 — Term 6 — Future tense
  w("Year 7", "Term 6", "Future tense", "Medium", "je vais", "I am going"),
  w("Year 7", "Term 6", "Future tense", "Medium", "je vais porter", "I am going to wear"),
  w("Year 7", "Term 6", "Future tense", "High", "ça sera", "it will be"),

  ...YEAR8_WORDS,
  ...YEAR9_WORDS,
  ...YEAR9_MORE_ABLE_WORDS,
];

export const USE_DEMO_NAMES = false;

export const DEMO_NAMES = [
  "Sophie",
  "Jack",
  "Oliver",
  "Amélie",
  "Charlie",
  "Isabella",
  "Mohammed",
  "Freya",
  "Leo",
  "Mia",
  "Noah",
  "Priya",
];

/** @deprecated Prefer DEMO_NAMES + USE_DEMO_NAMES */
export const SEED_NAMES = DEMO_NAMES;

export function nextId() {
  return `w${++counter}`;
}

export {
  filterWords,
  toggleFilterValue,
  type FilterWordsOptions,
  type VocabFilter,
} from "./vocab-filter";

export {
  isGapFillPhrase,
  isWheelPlayableWord,
  pickPrompt,
  wheelPlayableWords,
} from "./wheel-prompt";
export type { PromptableWord } from "./wheel-prompt";

