import { type Word } from "./vocab-data";

let counter = 0;
const w = (
  term: string,
  topic: string,
  diff: Word["difficulty"],
  french: string,
  english: string,
): Word => ({
  id: `y9-${++counter}`,
  year: "Year 9",
  term,
  topic,
  difficulty: diff,
  french,
  english,
});

export const YEAR9_WORDS: Word[] = [
  // Term 1
  // Term 1 — Identity
  w("Term 1", "Identity", "Low", "je m'appelle …", "my name is"),
  w("Term 1", "Identity", "Low", "j'ai quatorze ans", "I am 14 years old"),
  w("Term 1", "Identity", "Low", "j'ai", "I have"),
  w("Term 1", "Identity", "Low", "les cheveux blonds, bruns, roux", "blond, brown, ginger hair"),
  w(
    "Term 1",
    "Identity",
    "Low",
    "les cheveux longs, courts, mi-longs",
    "long, short, mid-length hair",
  ),
  w("Term 1", "Identity", "Low", "les yeux marron, bleus, noisette…", "brown, blue, hazel eyes"),
  w("Term 1", "Identity", "Low", "je suis", "I am"),
  w("Term 1", "Identity", "Low", "grand(e), petit(e)", "tall, small"),
  w("Term 1", "Identity", "Low", "de taille moyenne", "of average height"),
  w("Term 1", "Identity", "Low", "un ado/ un adolescent", "a teenager"),
  w("Term 1", "Identity", "Low", "jeune", "young"),
  w("Term 1", "Identity", "Low", "un frère", "a brother"),
  w("Term 1", "Identity", "Low", "une sœur", "a sister"),
  w("Term 1", "Identity", "Low", "un demi-frère", "a step/half brother"),
  w("Term 1", "Identity", "Low", "une demi-sœur", "a step/half sister"),
  w("Term 1", "Identity", "Low", "mon père", "my father"),
  w("Term 1", "Identity", "Low", "ma mère", "my mother"),
  w("Term 1", "Identity", "High", "mon beau-père", "my step-father"),
  w("Term 1", "Identity", "High", "ma belle-mère", "my step-mother"),
  w("Term 1", "Identity", "Low", "j'habite", "I live"),
  w("Term 1", "Identity", "Low", "chez", "at (somebody)'s place"),
  w("Term 1", "Identity", "Low", "chez moi", "at my place/at home"),
  w("Term 1", "Identity", "Low", "chez mon père", "at my dad's place"),
  w("Term 1", "Identity", "Low", "avec", "with"),
  // Term 1 — Personality
  w("Term 1", "Personality", "Low", "je suis / je ne suis pas", "I am / I am not"),
  w("Term 1", "Personality", "Low", "je ne suis jamais", "I am never"),
  w("Term 1", "Personality", "High", "je peux être", "I can be"),
  w("Term 1", "Personality", "Low", "on dit que je suis", "people say that I am"),
  w("Term 1", "Personality", "Low", "il/elle est", "he/she is"),
  w("Term 1", "Personality", "High", "ils/elles sont", "they are"),
  w("Term 1", "Personality", "Low", "gentil/gentille", "kind"),
  w("Term 1", "Personality", "Low", "drôle, marrant(e)", "funny"),
  w("Term 1", "Personality", "Low", "intelligent", "clever"),
  w("Term 1", "Personality", "Low", "sportif/sportive", "sporty"),
  w("Term 1", "Personality", "Low", "fidèle", "loyal"),
  w("Term 1", "Personality", "Low", "mignon(ne)", "cute"),
  w("Term 1", "Personality", "Low", "heureux, heureuse", "happy"),
  w("Term 1", "Personality", "Low", "poli(e)", "polite"),
  w("Term 1", "Personality", "Low", "compréhensif/-ive", "understanding"),
  w("Term 1", "Personality", "Low", "généreux/-euse", "generous"),
  w("Term 1", "Personality", "Low", "branché(e)", "trendy"),
  w("Term 1", "Personality", "Low", "timide", "shy"),
  w("Term 1", "Personality", "Low", "bavard(e)", "chatty"),
  w("Term 1", "Personality", "Low", "casse-pieds, pénible", "annoying"),
  w("Term 1", "Personality", "Low", "égoïste", "selfish"),
  w("Term 1", "Personality", "Low", "sévère", "strict"),
  w("Term 1", "Personality", "Low", "jaloux / jalouse", "jealous"),
  w("Term 1", "Personality", "Low", "impoli(e)", "rude/impolite"),
  // Term 1 — Relationships
  w("Term 1", "Relationships", "Low", "je m'entends bien avec …", "I get on well with…"),
  w("Term 1", "Relationships", "Low", "je ne m'entends pas avec…", "I don't get on with…"),
  w("Term 1", "Relationships", "Low", "je me dispute avec …", "I argue with"),
  w("Term 1", "Relationships", "Low", "je ne me dispute jamais avec…", "I never argue with…"),
  w("Term 1", "Relationships", "High", "je me chamaille avec … *", "I bicker with…"),
  w("Term 1", "Relationships", "High", "je me fâche avec … *", "I get angry with…"),
  w("Term 1", "Relationships", "Low", "un(e) bon(ne) ami(e)", "a good friend"),
  w("Term 1", "Relationships", "Low", "mon meilleur copain", "my best friend (boy)"),
  w("Term 1", "Relationships", "Low", "ma meilleure copine", "my best friend (girl)"),
  w("Term 1", "Relationships", "Low", "mon petit ami/copain", "my boyfriend"),
  w("Term 1", "Relationships", "Low", "ma petite amie/copine", "my girlfriend"),
  w("Term 1", "Relationships", "Low", "écoute mes problèmes", "listens to my problems"),
  w(
    "Term 1",
    "Relationships",
    "Low",
    "parle de (tout) avec moi",
    "talks about (everything) with me",
  ),
  w("Term 1", "Relationships", "Low", "aide tout le monde", "helps everyone"),
  w("Term 1", "Relationships", "Low", "respecte mes opinions", "respects my opinions"),
  w("Term 1", "Relationships", "Low", "aime les mêmes choses", "likes the same things"),
  w("Term 1", "Relationships", "Low", "on (bavarde/rigole) ensemble", "we (chat/laugh) together"),
  w("Term 1", "Relationships", "Low", "on discute de", "we chat about"),
  w("Term 1", "Relationships", "Low", "je partage mes secrets avec…", "I share my secrets with…"),
  w("Term 1", "Relationships", "High", "je le/la trouve (drôle)", "I find him/her (funny)"),
  w("Term 1", "Relationships", "Low", "on va en ville", "we go to town"),
  // Term 1 — Personality
  w("Term 1", "Personality", "Medium", "plutôt", "rather"),
  w("Term 1", "Personality", "Medium", "assez", "quite"),
  w("Term 1", "Personality", "Medium", "très", "very"),
  w("Term 1", "Personality", "Medium", "vraiment", "really"),
  w("Term 1", "Personality", "High", "un peu", "a bit"),
  w("Term 1", "Personality", "Medium", "plus... que", "more… than"),
  w("Term 1", "Personality", "Medium", "moins… que", "less… than"),
  // Term 1 — Relationships
  w("Term 1", "Relationships", "Medium", "… me critique quand …", "…. criticises me when …"),
  // Term 2
  // Term 2 — School subjects
  w("Term 2", "School subjects", "Low", "les matières", "subjects"),
  w("Term 2", "School subjects", "Low", "les maths", "Maths"),
  w("Term 2", "School subjects", "Low", "les sciences", "Science"),
  w("Term 2", "School subjects", "Low", "l'anglais", "English"),
  w("Term 2", "School subjects", "Low", "le français", "French"),
  w("Term 2", "School subjects", "Low", "l'espagnol", "Spanish"),
  w("Term 2", "School subjects", "Low", "l'allemand", "German"),
  w("Term 2", "School subjects", "Low", "l'histoire", "History"),
  w("Term 2", "School subjects", "Low", "la géographie", "Geography"),
  w("Term 2", "School subjects", "Low", "l'informatique", "IT"),
  w("Term 2", "School subjects", "Low", "l'EPS", "PE"),
  w("Term 2", "School subjects", "Low", "le dessin", "Art"),
  // Term 2 — Opinions
  w("Term 2", "Opinions", "Low", "le/la prof est sévère", "the teacher is strict"),
  w("Term 2", "Opinions", "Low", "le/la prof est drôle/sympa", "the teacher is funny/nice"),
  w("Term 2", "Opinions", "Low", "le/la prof est motivant(e)", "the teacher is motivating"),
  w("Term 2", "Opinions", "Low", "le prof est compréhensif", "the teacher is understanding"),
  w("Term 2", "Opinions", "Low", "c'est utile", "it's useful"),
  w("Term 2", "Opinions", "Low", "c'est facile", "it's easy"),
  w("Term 2", "Opinions", "Low", "c'est intéressant", "it's interesting"),
  w("Term 2", "Opinions", "Low", "c'est pas mal", "it's not bad/ok"),
  w("Term 2", "Opinions", "Low", "c'est inutile", "it's pointless/useless"),
  w("Term 2", "Opinions", "Low", "c'est difficile", "it's difficult"),
  w("Term 2", "Opinions", "Low", "c'est pénible", "it's annoying"),
  w("Term 2", "Opinions", "Low", "c'est dur", "it's hard"),
  w("Term 2", "Opinions", "Low", "c'est vraiment nul", "it's really rubbish"),
  w("Term 2", "Opinions", "Low", "…pour moi", "... for me"),
  w("Term 2", "Opinions", "Low", "…pour mon avenir", "... for my future"),
  w("Term 2", "Opinions", "Low", "ça me rend …", "it makes me …"),
  w("Term 2", "Opinions", "Low", "heureux", "happy"),
  w("Term 2", "Opinions", "Low", "je m'entends avec le prof", "I get on with the teacher"),
  w("Term 2", "Opinions", "Low", "je me dispute avec le prof", "I argue with the teacher"),
  w("Term 2", "Opinions", "Low", "je suis fort en …", "I am strong at"),
  w("Term 2", "Opinions", "Low", "je suis faible en …", "I am weak at"),
  w(
    "Term 2",
    "Opinions",
    "High",
    "je ne comprends rien en …",
    "I don't understand anything in ...",
  ),
  w("Term 2", "Opinions", "Low", "je trouve le français(difficile)", "I find (French) difficult"),
  // Term 2 — School life
  w("Term 2", "School life", "Low", "je révise", "I revise"),
  w("Term 2", "School life", "Low", "je travaille", "I work"),
  w("Term 2", "School life", "Low", "je parle trop", "I talk too much"),
  w("Term 2", "School life", "Low", "je bavarde", "I chat"),
  w("Term 2", "School life", "Low", "je discute", "I discuss/talk/chat"),
  w("Term 2", "School life", "Low", "je rigole", "I laugh"),
  w("Term 2", "School life", "Low", "j'étudie", "I study"),
  w("Term 2", "School life", "Low", "je lis", "I read"),
  w("Term 2", "School life", "Low", "j'envoye (mes devoirs)", "I send (my homework)"),
  w("Term 2", "School life", "High", "je rencontre", "I meet"),
  w("Term 2", "School life", "Low", "Les devoirs", "homework"),
  w("Term 2", "School life", "Low", "Les cours", "lessons"),
  w("Term 2", "School life", "Low", "mon portable", "my phone"),
  w("Term 2", "School life", "Low", "mon ordinateur", "my computer"),
  w("Term 2", "School life", "Low", "le bâtiment", "the building"),
  w("Term 2", "School life", "Low", "le collège", "secondary school (Y7 to Y10)"),
  w("Term 2", "School life", "Low", "la bibliothèque", "the library"),
  w("Term 2", "School life", "Low", "la cour", "the playground"),
  w("Term 2", "School life", "Low", "la cantine", "the canteen"),
  w("Term 2", "School life", "Low", "une salle de classe", "a classroom"),
  w("Term 2", "School life", "Low", "le/la prof de (maths)", "the (maths) teacher"),
  w("Term 2", "School life", "Low", "le principal", "the headteacher"),
  w("Term 2", "School life", "Low", "les élèves", "the students"),
  w("Term 2", "School life", "Low", "un sixième (6ème)", "a year 7"),
  w("Term 2", "School life", "Low", "le bac / baccalauréat", "A-Levels"),
  w("Term 2", "School life", "Low", "un contrôle", "a test"),
  w("Term 2", "School life", "Low", "les livres", "books"),
  w("Term 2", "School life", "Low", "les cours", "lessons"),
  w("Term 2", "School life", "Low", "souvent", "often"),
  w("Term 2", "School life", "Low", "de temps en temps", "from time to time"),
  w("Term 2", "School life", "Low", "toujours", "always"),
  w("Term 2", "School life", "Low", "tous les jours", "everyday"),
  w("Term 2", "School life", "Low", "quelquefois", "sometimes"),
  w("Term 2", "School life", "Low", "je suis accro", "I am addicted"),
  w("Term 2", "School life", "Low", "je ne peux pas vivre sans", "I can't live without"),
  // Term 2 — Christmas
  w("Term 2", "Christmas", "Low", "Noël", "Christmas"),
  w("Term 2", "Christmas", "Low", "le sapin", "the Christmas tree"),
  w("Term 2", "Christmas", "Low", "la dinde", "the turkey"),
  w("Term 2", "Christmas", "Low", "le repas", "the meal"),
  w("Term 2", "Christmas", "Low", "les cadeaux", "the presents"),
  w("Term 2", "Christmas", "Low", "la buche de Noël", "the Christmas/Yule log"),
  w("Term 2", "Christmas", "Low", "le Réveillon", "Christmas eve"),
  w("Term 2", "Christmas", "Low", "le père Noël", "Father Christmas"),
  w("Term 2", "Christmas", "Low", "je décore", "I decorate"),
  w("Term 2", "Christmas", "Low", "je prépare", "I prepare"),
  w("Term 2", "Christmas", "Low", "je cuisine", "I cook"),
  w("Term 2", "Christmas", "Low", "je mange", "I eat"),
  w("Term 2", "Christmas", "Low", "j'achète", "I buy"),
  // Term 3
  // Term 3 — Celebrations
  w("Term 3", "Celebrations", "Low", "le jour de l'an", "New Year's Day"),
  w(
    "Term 3",
    "Celebrations",
    "Low",
    "la fête des Rois / l'Épiphanie",
    "Twelfth Night / Kings' day",
  ),
  w("Term 3", "Celebrations", "Low", "la Chandeleur", "French pancake day (2/02)"),
  w("Term 3", "Celebrations", "Low", "Mardi Gras", "carnival time / Shrove Tuesday"),
  w("Term 3", "Celebrations", "Low", "La Saint Valentin", "Valentine's day"),
  w("Term 3", "Celebrations", "Low", "le 1er avril", "April Fool's day"),
  w("Term 3", "Celebrations", "Low", "Pâques", "Easter"),
  w("Term 3", "Celebrations", "Low", "le 1er mai / la fête du travail", "May day / Labour day"),
  w("Term 3", "Celebrations", "Low", "la fête des mères", "Mother's day"),
  w("Term 3", "Celebrations", "Low", "la fête de la musique", "Music day"),
  w("Term 3", "Celebrations", "Low", "la fête nationale / le 14 juillet", "Bastille day"),
  w("Term 3", "Celebrations", "Low", "le réveillon de Noël", "Christmas eve"),
  w("Term 3", "Celebrations", "Low", "Noël", "Christmas"),
  w("Term 3", "Celebrations", "Low", "la galette des Rois", "King's cake"),
  w("Term 3", "Celebrations", "Low", "la fève", "the King cake's charm"),
  w("Term 3", "Celebrations", "Low", "les crêpes", "crêpes/pancakes"),
  w("Term 3", "Celebrations", "Low", "l'amour", "love"),
  w("Term 3", "Celebrations", "Low", "poisson d'avril !!", "April Fools !!"),
  w("Term 3", "Celebrations", "Low", "les blagues", "jokes"),
  w("Term 3", "Celebrations", "High", "les œufs en chocolat", "chocolate eggs"),
  w("Term 3", "Celebrations", "Low", "le chocolat", "chocolate"),
  w("Term 3", "Celebrations", "Low", "l'agneau", "lamb"),
  w("Term 3", "Celebrations", "Low", "dans le jardin", "in the garden"),
  w("Term 3", "Celebrations", "Low", "le muguet", "lily of the valley"),
  w("Term 3", "Celebrations", "Low", "le bonheur", "happiness"),
  w("Term 3", "Celebrations", "Low", "des cadeaux", "presents"),
  w("Term 3", "Celebrations", "Low", "le feu d'artifice", "fireworks"),
  w("Term 3", "Celebrations", "Low", "le défilé", "the military parade"),
  w("Term 3", "Celebrations", "Low", "dans la rue", "in the street"),
  w("Term 3", "Celebrations", "Low", "je décore", "I decorate"),
  w("Term 3", "Celebrations", "Low", "je prépare", "I prepare"),
  w("Term 3", "Celebrations", "Low", "je cuisine", "I cook"),
  w("Term 3", "Celebrations", "Low", "je mange", "I eat"),
  w("Term 3", "Celebrations", "Low", "je bois", "I drink"),
  w("Term 3", "Celebrations", "Low", "j'achète", "I buy"),
  w("Term 3", "Celebrations", "Low", "je trouve", "I find"),
  w("Term 3", "Celebrations", "Low", "je commande", "I order"),
  w("Term 3", "Celebrations", "Low", "je danse", "I dance"),
  w("Term 3", "Celebrations", "Low", "je chante", "I sing"),
  w("Term 3", "Celebrations", "Low", "je blague", "I joke"),
  w("Term 3", "Celebrations", "Low", "je fête", "I celebrate"),
  w("Term 3", "Celebrations", "Low", "je regarde", "I watch"),
  // Term 3 — Past tense
  w("Term 3", "Past tense", "Low", "j'ai décoré", "I decorate"),
  w("Term 3", "Past tense", "Low", "j'ai acheté", "I bought"),
  w("Term 3", "Past tense", "Low", "j'ai partagé", "I shared"),
  w("Term 3", "Past tense", "Low", "j'ai cuisiné", "I cooked"),
  w("Term 3", "Past tense", "High", "je suis allé", "I went"),
  w("Term 3", "Past tense", "High", "j'ai bu", "I drank"),
  w("Term 3", "Past tense", "High", "j'ai vu", "I saw"),
  w("Term 3", "Past tense", "High", "j'ai fait", "I did"),
  w("Term 3", "Past tense", "Low", "c'était", "it was"),
  // Term 3 — Future tense
  w("Term 3", "Future tense", "Low", "je vais préparer", "I'm going to prepare"),
  w("Term 3", "Future tense", "Low", "je vais fêter", "I'm going to celebrate"),
  w("Term 3", "Future tense", "Low", "je vais chanter", "I'm going to sing"),
  w("Term 3", "Future tense", "Low", "ça sera", "it will be"),
  // Term 3 — Past tense
  w("Term 3", "Past tense", "Medium", "j'ai décoré", "I decorated"),
  // Term 4
  // Term 4 — At the restaurant
  w("Term 4", "At the restaurant", "Low", "les légumes", "vegetables"),
  w("Term 4", "At the restaurant", "High", "des crudités", "salad / raw vegetables"),
  w("Term 4", "At the restaurant", "Low", "des pommes de terre", "potatoes"),
  w("Term 4", "At the restaurant", "Low", "des petit-pois", "peas"),
  w("Term 4", "At the restaurant", "Low", "des haricots verts", "green beans"),
  w("Term 4", "At the restaurant", "Low", "de la", "ratatouilleratatouille"),
  w("Term 4", "At the restaurant", "Low", "la viande", "meat"),
  w("Term 4", "At the restaurant", "Low", "du porc", "pork"),
  w("Term 4", "At the restaurant", "Low", "du bœuf", "beef"),
  w("Term 4", "At the restaurant", "Low", "des saucisses", "sausages"),
  w("Term 4", "At the restaurant", "Low", "du poulet", "chicken"),
  w("Term 4", "At the restaurant", "Low", "du steak haché", "burger meat"),
  w("Term 4", "At the restaurant", "Low", "du jambon", "ham"),
  w("Term 4", "At the restaurant", "Low", "des frites", "chips"),
  w("Term 4", "At the restaurant", "Low", "des chips", "crisps"),
  w("Term 4", "At the restaurant", "Low", "une quiche", "a quiche"),
  w("Term 4", "At the restaurant", "Low", "des pâtes", "pasta"),
  w("Term 4", "At the restaurant", "Low", "des plats chinois", "chinese dishes"),
  w("Term 4", "At the restaurant", "High", "des fruits de mer", "seafood"),
  w("Term 4", "At the restaurant", "Low", "du poisson", "fish"),
  w("Term 4", "At the restaurant", "Low", "du saumon", "salmon"),
  w("Term 4", "At the restaurant", "High", "du thon", "tuna"),
  w("Term 4", "At the restaurant", "Low", "des escargots", "snails"),
  w("Term 4", "At the restaurant", "Low", "un couscous tunisien", "a Tunisian couscous dish"),
  w("Term 4", "At the restaurant", "Low", "le pain", "bread"),
  w("Term 4", "At the restaurant", "Low", "du fromage", "cheese      du brie, du camembert"),
  w("Term 4", "At the restaurant", "Low", "du yaourt", "yoghurt"),
  w("Term 4", "At the restaurant", "Low", "de la glace", "ice cream"),
  w("Term 4", "At the restaurant", "Low", "du sucre", "sugar"),
  w("Term 4", "At the restaurant", "Low", "des", "fruitsfruit"),
  w("Term 4", "At the restaurant", "Low", "des fraises", "strawberries"),
  w("Term 4", "At the restaurant", "Low", "du citron", "lemon"),
  w("Term 4", "At the restaurant", "Low", "une pomme", "an apple"),
  w("Term 4", "At the restaurant", "High", "de l'ananas", "pineapple"),
  w("Term 4", "At the restaurant", "Low", "les boissons", "drinks"),
  w("Term 4", "At the restaurant", "Low", "du vin", "wine"),
  w("Term 4", "At the restaurant", "Low", "de l'eau", "water"),
  w("Term 4", "At the restaurant", "Low", "du lait", "milk"),
  w("Term 4", "At the restaurant", "Low", "un peu de", "a bit of"),
  w("Term 4", "At the restaurant", "Low", "beaucoup de", "a lot of"),
  w("Term 4", "At the restaurant", "Low", "trop de", "too much"),
  w("Term 4", "At the restaurant", "Low", "je mange", "I eat"),
  w("Term 4", "At the restaurant", "Low", "je bois", "I drink"),
  w("Term 4", "At the restaurant", "Low", "je commande", "I order"),
  w("Term 4", "At the restaurant", "Low", "je paye", "I pay"),
  w("Term 4", "At the restaurant", "Low", "je cuisine", "I cook"),
  w("Term 4", "At the restaurant", "Low", "je prépare", "I prepare"),
  w("Term 4", "At the restaurant", "Low", "mon plat préféré", "my favourite dish"),
  w("Term 4", "At the restaurant", "Low", "la nourriture", "food"),
  w("Term 4", "At the restaurant", "Low", "le repas", "the meal"),
  w("Term 4", "At the restaurant", "Low", "la cuisine traditionnelle", "traditional food"),
  w("Term 4", "At the restaurant", "Low", "l'addition", "the bill"),
  w("Term 4", "At the restaurant", "Low", "le serveur", "the waiter"),
  w("Term 4", "At the restaurant", "Low", "c'est délicieux", "it's delicious"),
  w("Term 4", "At the restaurant", "Medium", "c'est dégoûtant", "it's disgusting"),
  w("Term 4", "At the restaurant", "Low", "c'est trop salé/sucré", "it's too salty/sweet"),
  w("Term 4", "At the restaurant", "Low", "c'est épicé", "it's spicy"),
  w("Term 4", "At the restaurant", "Low", "c'est trop cuit", "it's overcooked"),
  w("Term 4", "At the restaurant", "High", "c'est incroyable", "it's incredible"),
  w("Term 4", "At the restaurant", "High", "c'est inoubliable", "it's unforgettable"),
  w("Term 4", "At the restaurant", "Low", "c'est mémorable", "it's memorable"),
  w("Term 4", "At the restaurant", "High", "c'est immangeable", "it's inedible"),
  // Term 4 — Past tense
  w("Term 4", "Past tense", "Low", "j'ai regardé le menu", "I looked at the menu"),
  w("Term 4", "Past tense", "Low", "j'ai commandé (un plat)", "I ordered (a dish)"),
  w("Term 4", "Past tense", "Low", "j'ai payé (mon dessert)", "I paid (for my dessert)"),
  w("Term 4", "Past tense", "Low", "j'ai blagué avec le chef", "I joked with the chef"),
  w("Term 4", "Past tense", "High", "j'ai essayé", "I tried"),
  // Term 5
  // Term 5 — Leisure
  w("Term 5", "Leisure", "Low", "les actualités", "the news"),
  w("Term 5", "Leisure", "Low", "le journal", "the newspaper / the (TV) news"),
  w("Term 5", "Leisure", "Low", "les dessin-animés", "cartoons"),
  w("Term 5", "Leisure", "Low", "les séries", "series"),
  w("Term 5", "Leisure", "Low", "une émissions de sport", "a sport programme"),
  w("Term 5", "Leisure", "Low", "la télé-réalité", "reality TV"),
  w("Term 5", "Leisure", "Low", "les magazines culturels", "magazine programmes"),
  w("Term 5", "Leisure", "Low", "les jeux télévisés", "game shows"),
  w("Term 5", "Leisure", "Low", "un film de guerre", "a war film"),
  w("Term 5", "Leisure", "Low", "un film d'amour", "a love film"),
  w("Term 5", "Leisure", "Low", "un film policier", "a detective story"),
  w("Term 5", "Leisure", "Low", "je regarde", "I watch"),
  w("Term 5", "Leisure", "Low", "je télécharge", "I download"),
  w("Term 5", "Leisure", "High", "j'apprends", "I learn"),
  w("Term 5", "Leisure", "High", "je ne rate jamais", "I never miss"),
  w("Term 5", "Leisure", "Low", "je pense que", "I think that"),
  w("Term 5", "Leisure", "Low", "c'est intéressant", "it's interesting"),
  w("Term 5", "Leisure", "Low", "c'est passionnant", "it's exciting"),
  w("Term 5", "Leisure", "Low", "c'est barbant", "it's boring"),
  w("Term 5", "Leisure", "Low", "c'est éducatif", "it's educational"),
  w("Term 5", "Leisure", "Low", "c'est divertissant", "it's entertaining"),
  w("Term 5", "Leisure", "Low", "c'est ludique", "it's fun"),
  w("Term 5", "Leisure", "Low", "c'est trop sérieux", "it's too serious"),
  w("Term 5", "Leisure", "High", "c'est effrayant", "it's frightening"),
  w("Term 5", "Leisure", "Low", "le", "sportsport"),
  w("Term 5", "Leisure", "Low", "je joue au / à la + ball sports", "I play"),
  w("Term 5", "Leisure", "Low", "je fais du/ de la + non-ball", "sportsI do"),
  w("Term 5", "Leisure", "Low", "…depuis 3 ans", "for 3 years"),
  w("Term 5", "Leisure", "Low", "dans une équipe", "in a team"),
  w("Term 5", "Leisure", "High", "je m'entraine", "I train"),
  w("Term 5", "Leisure", "Low", "je marche", "I walk"),
  w("Term 5", "Leisure", "Low", "je nage", "I swim"),
  w("Term 5", "Leisure", "Low", "quand je peux", "when I can"),
  w("Term 5", "Leisure", "Low", "si je veux", "if I want"),
  w("Term 5", "Leisure", "Low", "l'escalade", "rock climbing"),
  w("Term 5", "Leisure", "Low", "la natation", "swimming"),
  w("Term 5", "Leisure", "Low", "l'équitation", "horseriding"),
  w("Term 5", "Leisure", "Low", "la randonnée", "hiking"),
  w("Term 5", "Leisure", "Low", "la voile", "sailing"),
  w("Term 5", "Leisure", "High", "un vrai défi", "a real challenge"),
  w(
    "Term 5",
    "Leisure",
    "Low",
    "c'est bon pour le corps, le mental",
    "it's good for the body/mind",
  ),
  w("Term 5", "Leisure", "Low", "ça booste le moral", "it boosts my mood"),
  w("Term 5", "Leisure", "Low", "la lecture", "reading"),
  w("Term 5", "Leisure", "Low", "un livre", "a book"),
  w("Term 5", "Leisure", "Low", "les romans", "novels"),
  w("Term 5", "Leisure", "Low", "les romans fantastiques", "fantasy novels"),
  w("Term 5", "Leisure", "Low", "les romans d'amour", "love novels"),
  w("Term 5", "Leisure", "Low", "les BD", "comics"),
  w("Term 5", "Leisure", "Low", "les mangas", "mangas/animés"),
  w("Term 5", "Leisure", "Low", "j'ai une passion pour", "I have a passion for"),
  w("Term 5", "Leisure", "Low", "j'ai horreur de", "I can't stand"),
  w("Term 5", "Leisure", "Low", "sur un écran/une tablette", "on a screen/a tablet"),
  w("Term 5", "Leisure", "Low", "la musique", "music"),
  w("Term 5", "Leisure", "Low", "j'écoute de la musique", "I listen to music"),
  w("Term 5", "Leisure", "Low", "je chante", "I sing"),
  w("Term 5", "Leisure", "Low", "les paroles", "the lyrics"),
  w("Term 5", "Leisure", "Low", "ça me rend triste/heureux", "it makes me sad/happy"),
  w("Term 5", "Leisure", "Low", "mon chanteur préféré", "my favourite singer"),
  w("Term 5", "Leisure", "Low", "une chanson", "a song"),
  // Term 6
  // Term 6 — Infinitives
  w("Term 6", "Infinitives", "Medium", "Télécharger", "To download"),
  w("Term 6", "Infinitives", "Medium", "Partager", "To share"),
  w("Term 6", "Infinitives", "Medium", "bavarder", "To chat"),
  w("Term 6", "Infinitives", "Medium", "étudier", "To study"),
  w("Term 6", "Infinitives", "Medium", "Regarder", "To watch"),
  w("Term 6", "Infinitives", "Medium", "travailler", "To work"),
  w("Term 6", "Infinitives", "Medium", "Écouter", "To listen"),
  w("Term 6", "Infinitives", "Medium", "Jouer", "To play"),
  w("Term 6", "Infinitives", "Medium", "Acheter", "To buy"),
  w("Term 6", "Infinitives", "Medium", "Commander", "To order"),
  w("Term 6", "Infinitives", "Medium", "Préparer", "To prepare"),
  w("Term 6", "Infinitives", "Medium", "Boire", "To drink"),
  w("Term 6", "Infinitives", "Medium", "Manger", "To eat"),
  w("Term 6", "Infinitives", "Medium", "marcher", "To walk"),
  w("Term 6", "Infinitives", "Medium", "nager", "To swim"),
  w("Term 6", "Infinitives", "Medium", "fêter", "To celebrate"),
  w("Term 6", "Infinitives", "Medium", "Cuisine", "To cook"),
  w("Term 6", "Infinitives", "Medium", "Décorer", "To decorate"),
  w("Term 6", "Infinitives", "Medium", "trouver", "To find"),
  w("Term 6", "Infinitives", "Medium", "Danser", "To dance"),
  w("Term 6", "Infinitives", "Medium", "chanter", "to sing"),
  w("Term 6", "Infinitives", "Medium", "rigoler", "To laugh"),
  w("Term 6", "Infinitives", "Medium", "blaguer", "to joke"),
  w("Term 6", "Infinitives", "Medium", "S’entendre", "To get on"),
  w("Term 6", "Infinitives", "Medium", "Se disputer", "To argue"),
  w("Term 6", "Infinitives", "High", "Se chamailler", "to bicker"),
  w("Term 6", "Infinitives", "High", "se fâcher", "to get angry"),
  w("Term 6", "Infinitives", "High", "Faire", "To do"),
  w("Term 6", "Infinitives", "High", "Aller", "to go"),
  // Term 6 — Fashion
  w("Term 6", "Fashion", "Low", "les vêtements", "clothes"),
  w("Term 6", "Fashion", "Low", "une taille", "a size"),
  w("Term 6", "Fashion", "Low", "je porte", "I wear"),
  w("Term 6", "Fashion", "Low", "en hiver", "in winter"),
  w("Term 6", "Fashion", "Low", "un pull", "a jumper"),
  w("Term 6", "Fashion", "Low", "un pull à capuche", "a hoodie"),
  w("Term 6", "Fashion", "Low", "des bottes", "boots"),
  w("Term 6", "Fashion", "High", "un manteau", "a coat"),
  w("Term 6", "Fashion", "Low", "en été", "in summer"),
  w("Term 6", "Fashion", "Low", "un", "shortshorts"),
  w("Term 6", "Fashion", "Low", "un T-shirt", "a T-shirt"),
  w("Term 6", "Fashion", "Low", "une jupe", "a skirt"),
  w("Term 6", "Fashion", "Low", "une robe", "a dress"),
  w("Term 6", "Fashion", "Low", "un chapeau", "a hat"),
  w("Term 6", "Fashion", "Low", "des lunettes de soleil", "sunglasses"),
  w("Term 6", "Fashion", "Low", "au collège", "at school"),
  w("Term 6", "Fashion", "Low", "un pantalon", "trousers"),
  w("Term 6", "Fashion", "Low", "une chemise", "a shirt"),
  w("Term 6", "Fashion", "Low", "une cravate", "a tie"),
  w("Term 6", "Fashion", "Low", "une veste", "a blazer"),
  w("Term 6", "Fashion", "Low", "des chaussettes", "socks"),
  w("Term 6", "Fashion", "Low", "des chaussures", "shoes"),
  w("Term 6", "Fashion", "Low", "le week end", "at the weekend"),
  w("Term 6", "Fashion", "Low", "un jean", "jeans"),
  w("Term 6", "Fashion", "Low", "un sac (à main)", "a (hand)bag"),
  w("Term 6", "Fashion", "High", "un sac (à dos)", "a ruck sack"),
  w("Term 6", "Fashion", "Low", "des baskets", "trainers"),
  w("Term 6", "Fashion", "Low", "c'est chic", "it's smart"),
  w("Term 6", "Fashion", "Low", "c'est branché", "it's trendy"),
  // Term 6 — Infinitives
  w("Term 6", "Infinitives", "Low", "Se c", "hamailler"),
  w("Term 6", "Infinitives", "Low", "Je me c", "hamaille"),
  w("Term 6", "Infinitives", "Low", "c'était (", "it was)"),
  w("Term 6", "Infinitives", "Low", "ca sera (", "it will be)"),
];
