import { type Word } from "./vocab-data";

let counter = 0;
const w = (
  term: string,
  topic: string,
  diff: Word["difficulty"],
  french: string,
  english: string,
  image?: string,
): Word => ({
  id: `y8-${++counter}`,
  year: "Year 8",
  term,
  topic,
  difficulty: diff,
  french,
  english,
  ...(image ? { image } : {}),
});

export const YEAR8_WORDS: Word[] = [
  // Term 1 — Personality
  w("Term 1", "Personality", "Low", "Je suis", "I am"),
  w("Term 1", "Personality", "Low", "Je ne suis pas", "I am not"),
  w("Term 1", "Personality", "High", "Je peux être", "I can be"),
  w("Term 1", "Personality", "High", "je ne suis jamais", "I am never"),
  w("Term 1", "Personality", "Low", "Il/elle est …", "He/she is …"),
  w("Term 1", "Personality", "High", "même si …", "even if …"),
  w("Term 1", "Personality", "High", "on dit que", "people say that"),
  w("Term 1", "Personality", "High", "je suis d'accord", "I agree"),
  w("Term 1", "Personality", "High", "je ne suis pas d'accord", "I don't agree"),
  w("Term 1", "Personality", "Medium", "intelligent(e)", "intelligent"),
  w("Term 1", "Personality", "Low", "gentil(le)", "kind"),
  w("Term 1", "Personality", "Low", "sympa", "friendly/nice"),
  w("Term 1", "Personality", "Low", "bavard(e)", "chatty"),
  w("Term 1", "Personality", "Medium", "bien organisé(e)", "well organised"),
  w("Term 1", "Personality", "Low", "paresseux(se)", "lazy"),
  w("Term 1", "Personality", "Medium", "généreux(se)", "generous"),
  w("Term 1", "Personality", "Low", "très", "very"),
  w("Term 1", "Personality", "Low", "plutôt", "rather"),
  w("Term 1", "Personality", "Low", "vraiment", "really"),
  w("Term 1", "Personality", "Low", "un peu", "a bit"),
  w("Term 1", "Personality", "Medium", "sportif(ve)", "sporty"),
  w("Term 1", "Personality", "Low", "drôle / marrant(e)", "funny"),
  w("Term 1", "Personality", "Low", "égoïste", "selfish"),
  w("Term 1", "Personality", "Medium", "patient(e)", "patient"),
  w("Term 1", "Personality", "Medium", "timide", "shy"),
  w("Term 1", "Personality", "Medium", "branché", "trendy"),
  w("Term 1", "Personality", "Low", "pénible", "annoying"),

  // Term 1 — Physical description recap
  w("Term 1", "Physical description recap", "Low", "J'ai", "I have"),
  w("Term 1", "Physical description recap", "Low", "Il/elle a", "he/she has"),
  w("Term 1", "Physical description recap", "Low", "Les yeux", "eyes"),
  w("Term 1", "Physical description recap", "Low", "Les cheveux", "hair"),

  // Term 1 — Relationships
  w("Term 1", "Relationships", "Low", "Ma mère", "my mum"),
  w("Term 1", "Relationships", "Low", "Mon père", "my dad"),
  w("Term 1", "Relationships", "Low", "Mon frère", "my brother"),
  w("Term 1", "Relationships", "Low", "Ma soeur", "my sister"),
  w("Term 1", "Relationships", "Medium", "Ma grand-mère", "my grandmother"),
  w("Term 1", "Relationships", "Low", "Mon grand-père", "my granddad"),
  w("Term 1", "Relationships", "Low", "Ma belle-mère", "my stepmum"),
  w("Term 1", "Relationships", "Low", "Mon beau-père", "my stepdad"),
  w("Term 1", "Relationships", "Low", "Je m'entends bien avec …", "I get on well with …"),
  w(
    "Term 1",
    "Relationships",
    "Low",
    "Je ne m'entends pas bien avec …",
    "I do not get on well with …",
  ),
  w("Term 1", "Relationships", "Low", "Je me dispute (beaucoup) avec …", "I argue (a lot) with …"),
  w("Term 1", "Relationships", "Medium", "Je ne me dispute pas avec …", "I do not argue with …"),
  w("Term 1", "Relationships", "High", "Je ne me dispute jamais avec …", "I never argue with …"),
  w("Term 1", "Relationships", "Medium", "car / parce que …", "because …"),
  w("Term 1", "Relationships", "Medium", "on joue ensemble", "we play together"),
  w("Term 1", "Relationships", "Medium", "elle/il est trop sévère", "she/he is too strict"),
  w(
    "Term 1",
    "Relationships",
    "Medium",
    "il/elle n'aide pas à la maison",
    "he/she does not help at home",
  ),
  w(
    "Term 1",
    "Relationships",
    "Medium",
    "il/elle me critique tout le temps",
    "he/she criticises me all the time",
  ),
  w(
    "Term 1",
    "Relationships",
    "Medium",
    "il aide (avec mes devoirs)",
    "he helps (with my homework)",
  ),
  w("Term 1", "Relationships", "Medium", "on aime la même musique", "we like the same music"),
  w(
    "Term 1",
    "Relationships",
    "Medium",
    "il/elle respecte mes opinions",
    "he/she respects my opinions",
  ),
  w("Term 1", "Relationships", "High", "on aime les mêmes choses", "we like the same things"),
  w("Term 1", "Relationships", "High", "il/elle m'écoute", "he/she listens to me"),
  w("Term 1", "Relationships", "High", "quand j'ai des problèmes", "when I have problems"),
  w(
    "Term 1",
    "Relationships",
    "High",
    "je peux lui parler de tout",
    "I can discuss everything with him/her",
  ),

  // Term 1 — Together we
  w("Term 1", "Together we", "Medium", "Avec mes copains / amis …", "with my friends …"),
  w("Term 1", "Together we", "Medium", "on va en ville", "we go to town"),
  w("Term 1", "Together we", "Low", "on va au cinéma", "we go to the cinema"),
  w("Term 1", "Together we", "Low", "on va au parc", "we go to the park"),
  w("Term 1", "Together we", "Medium", "on écoute de la musique", "we listen to music"),
  w("Term 1", "Together we", "Medium", "on joue à des jeux vidéos", "we play video games"),
  w("Term 1", "Together we", "Medium", "on joue au foot", "we play football"),
  w("Term 1", "Together we", "Medium", "on fait du shopping", "we go shopping"),
  w("Term 1", "Together we", "Medium", "on rigole", "we laugh"),
  w("Term 1", "Together we", "Medium", "on regarde la télé / des films", "we watch TV/films"),
  w("Term 1", "Together we", "Medium", "on parle de sport", "we talk about sport"),
  w("Term 1", "Together we", "Medium", "on parle de mode", "we talk about fashion"),
  w("Term 1", "Together we", "Medium", "on parle de films", "we talk about films"),
  w("Term 1", "Together we", "Medium", "on parle de musique", "we talk about music"),

  // Term 1 — Weather
  w("Term 1", "Weather", "Medium", "Il fait beau", "it is sunny (beautiful weather)"),
  w("Term 1", "Weather", "Low", "Il fait chaud", "it is hot"),
  w("Term 1", "Weather", "Medium", "quand …", "when …"),
  w("Term 1", "Weather", "Low", "Il fait froid", "it's cold"),
  w("Term 1", "Weather", "Medium", "si …", "if …"),
  w("Term 1", "Weather", "Low", "Il pleut", "it is raining"),
  w("Term 1", "Weather", "Medium", "Il neige", "it is snowing"),
  w("Term 1", "Weather", "Low", "il y a du soleil", "it is sunny"),

  // Term 2 — Seasons
  w("Term 2", "Seasons", "Low", "en été", "in the summer"),
  w("Term 2", "Seasons", "Low", "en hiver", "in the winter"),
  w("Term 2", "Seasons", "Medium", "Quand il fait beau", "when the weather is nice"),

  // Term 2 — Sport
  w("Term 2", "Sport", "Medium", "le foot", "football"),
  w("Term 2", "Sport", "Medium", "le rugby", "rugby"),
  w("Term 2", "Sport", "Medium", "le tennis", "tennis"),
  w("Term 2", "Sport", "Medium", "le basket(ball)", "basketball"),
  w("Term 2", "Sport", "Medium", "le badminton", "badminton"),
  w("Term 2", "Sport", "Medium", "le handball", "handball"),
  w("Term 2", "Sport", "Medium", "le cricket", "cricket"),
  w("Term 2", "Sport", "Medium", "la pétanque / les boules", "bowls (French bowls)"),
  w("Term 2", "Sport", "Low", "Je joue au foot", "I play football"),
  w("Term 2", "Sport", "Low", "Je joue à la pétanque", "I play bowls"),
  w("Term 2", "Sport", "Low", "Je joue aux boules", "I play bowls"),
  w("Term 2", "Sport", "Medium", "mon sport préféré, c'est …", "my favourite sport is …"),
  w(
    "Term 2",
    "Sport",
    "Medium",
    "mon sportif préféré s'appelle",
    "my favourite sportsman is called",
  ),
  w("Term 2", "Sport", "Medium", "dans une équipe", "in a team"),
  w("Term 2", "Sport", "Low", "l'équitation", "horse riding"),
  w("Term 2", "Sport", "Low", "la natation", "swimming"),
  w("Term 2", "Sport", "Medium", "la danse", "dance"),
  w("Term 2", "Sport", "Medium", "le patin à glace", "ice skating"),
  w("Term 2", "Sport", "Medium", "le parkour", "parkour/free running"),
  w("Term 2", "Sport", "Medium", "le jogging", "running/jogging"),
  w("Term 2", "Sport", "Medium", "le ski", "ski"),
  w("Term 2", "Sport", "Medium", "le trampoline", "trampoline"),
  w("Term 2", "Sport", "Medium", "une promenade", "a walk"),
  w("Term 2", "Sport", "High", "je marche", "I walk"),
  w("Term 2", "Sport", "Low", "Je fais du parkour", "I do parkour"),
  w("Term 2", "Sport", "Medium", "Je fais de l'équitation", "I do horse riding"),
  w("Term 2", "Sport", "Medium", "Je fais de la natation", "I do swimming"),

  // Term 2 — Film genres
  w("Term 2", "Film genres", "Medium", "les films fantastiques", "fantasy films"),
  w("Term 2", "Film genres", "Medium", "les films de science-fiction", "sci-fi films"),
  w("Term 2", "Film genres", "Medium", "les films de guerre", "war films"),
  w("Term 2", "Film genres", "Medium", "les films d'amour", "love films"),
  w("Term 2", "Film genres", "Medium", "les films romantiques", "romantic films"),
  w("Term 2", "Film genres", "Medium", "les films d'horreur", "horror films"),
  w("Term 2", "Film genres", "Medium", "les films d'action", "action films"),
  w("Term 2", "Film genres", "Medium", "les films d'aventure", "adventure films"),
  w("Term 2", "Film genres", "Medium", "les films d'arts-martiaux", "martial arts films"),
  w("Term 2", "Film genres", "Medium", "les comédies", "comedies"),
  w("Term 2", "Film genres", "Medium", "les dessins animés", "cartoons"),

  // Term 2 — Film opinions
  w("Term 2", "Film opinions", "Medium", "Je regarde", "I watch"),
  w("Term 2", "Film opinions", "Medium", "Je ne regarde pas", "I don't watch"),
  w("Term 2", "Film opinions", "High", "Je ne regarde jamais", "I never watch"),
  w("Term 2", "Film opinions", "Medium", "regarder", "to watch"),
  w("Term 2", "Film opinions", "Medium", "J'aime regarder", "I like to watch"),
  w("Term 2", "Film opinions", "Medium", "Je n'aime pas regarder", "I don't like to watch"),
  w("Term 2", "Film opinions", "Medium", "J'aime beaucoup …", "I like a lot …"),
  w("Term 2", "Film opinions", "Medium", "Je suis fan de …", "I am a fan of …"),
  w("Term 2", "Film opinions", "Medium", "J'ai une passion pour …", "I have a passion for …"),
  w("Term 2", "Film opinions", "High", "J'ai horreur des …", "I can't stand …"),
  w("Term 2", "Film opinions", "Medium", "Mon acteur préféré c'est …", "my favourite actor is …"),

  // Term 2 — Adverbs of frequency
  w("Term 2", "Adverbs of frequency", "Medium", "tous les soirs", "every night"),
  w("Term 2", "Adverbs of frequency", "Medium", "tous les jours", "every day"),
  w("Term 2", "Adverbs of frequency", "Medium", "tous les weekends", "every weekend"),
  w("Term 2", "Adverbs of frequency", "Medium", "tout le temps", "all the time"),
  w("Term 2", "Adverbs of frequency", "Medium", "souvent", "often"),
  w("Term 2", "Adverbs of frequency", "Medium", "quelquefois", "sometimes"),

  // Term 3 — Music
  w("Term 3", "Music", "Medium", "du R'n'B", "R'n'B"),
  w("Term 3", "Music", "Medium", "du rock", "rock"),
  w("Term 3", "Music", "Medium", "de la pop", "pop"),
  w("Term 3", "Music", "Medium", "de la musique classique", "classical music"),
  w("Term 3", "Music", "Medium", "du zouk", "zouk"),
  w("Term 3", "Music", "Medium", "du rap", "rap"),
  w("Term 3", "Music", "Medium", "J'écoute", "I listen"),
  w("Term 3", "Music", "Medium", "Je n'écoute pas", "I don't listen"),
  w("Term 3", "Music", "Medium", "J'aime écouter", "I like to listen"),
  w("Term 3", "Music", "Medium", "Je chante", "I sing"),
  w("Term 3", "Music", "Medium", "Je danse", "I dance"),
  w("Term 3", "Music", "Medium", "Je télécharge", "I download"),
  w("Term 3", "Music", "Medium", "Je ne télécharge jamais", "I never download"),
  w("Term 3", "Music", "Medium", "les mélodies", "the tunes"),
  w("Term 3", "Music", "Medium", "les paroles", "the lyrics"),
  w("Term 3", "Music", "Medium", "la chanson", "the song"),
  w("Term 3", "Music", "Medium", "les chorégraphies", "choreographies"),
  w("Term 3", "Music", "Medium", "beaucoup d'artistes différents", "a lot of different artists"),
  w(
    "Term 3",
    "Music",
    "Medium",
    "Mon chanteur préféré / ma chanteuse préférée est",
    "my favourite singer is",
  ),
  w("Term 3", "Music", "Medium", "Mon groupe préféré est", "my favourite group is"),
  w("Term 3", "Music", "High", "ça me rend", "it makes me"),
  w("Term 3", "Music", "Medium", "triste", "sad"),
  w("Term 3", "Music", "Medium", "joyeux(se)", "happy"),
  w("Term 3", "Music", "High", "ça me donne envie de + INF", "it makes me want to + INF"),
  w("Term 3", "Music", "Medium", "pleurer", "to cry"),
  w("Term 3", "Music", "Medium", "danser", "to dance"),
  w("Term 3", "Music", "Medium", "chanter", "to sing"),
  w("Term 3", "Music", "Medium", "télécharger", "to download"),

  // Term 3 — Monuments of Paris
  w(
    "Term 3",
    "Monuments of Paris",
    "Medium",
    "la tour Eiffel",
    "the Eiffel Tower",
    "/vocab-images/year8/eiffel-tower.jpg",
  ),
  w(
    "Term 3",
    "Monuments of Paris",
    "Medium",
    "la cathédrale Notre-Dame",
    "Notre-Dame Cathedral",
    "/vocab-images/year8/notre-dame.png",
  ),
  w(
    "Term 3",
    "Monuments of Paris",
    "Medium",
    "l'Arc de Triomphe",
    "the Arc de Triomphe",
    "/vocab-images/year8/arc-de-triomphe.png",
  ),
  w("Term 3", "Monuments of Paris", "Medium", "les Champs-Elysées", "the Champs-Élysées"),
  w(
    "Term 3",
    "Monuments of Paris",
    "Medium",
    "le Louvre",
    "the Louvre",
    "/vocab-images/year8/louvre.jpg",
  ),
  w(
    "Term 3",
    "Monuments of Paris",
    "Medium",
    "le Moulin Rouge",
    "the Moulin Rouge",
    "/vocab-images/year8/moulin-rouge.jpg",
  ),
  w("Term 3", "Monuments of Paris", "Medium", "le Sacré-Cœur", "the Sacré-Cœur"),
  w("Term 3", "Monuments of Paris", "Medium", "la Seine", "the Seine"),

  // Term 4 — In Paris past tense
  w("Term 4", "In Paris past tense", "Low", "J'ai visité …", "I (have) visited …"),
  w("Term 4", "In Paris past tense", "High", "Je n'ai pas visité …", "I have not visited …"),
  w("Term 4", "In Paris past tense", "High", "Je n'ai jamais visité …", "I have never visited …"),
  w("Term 4", "In Paris past tense", "Medium", "J'ai admiré …", "I (have) admired …"),
  w("Term 4", "In Paris past tense", "Low", "J'ai regardé …", "I (have) watched …"),
  w("Term 4", "In Paris past tense", "Medium", "J'ai acheté …", "I (have) bought …"),
  w("Term 4", "In Paris past tense", "Low", "J'ai mangé …", "I (have) eaten …"),
  w("Term 4", "In Paris past tense", "Medium", "J'ai rencontré …", "I (have) met …"),
  w("Term 4", "In Paris past tense", "Medium", "J'ai envoyé …", "I (have) sent …"),
  w("Term 4", "In Paris past tense", "High", "On a admiré …", "we have admired …"),
  w("Term 4", "In Paris past tense", "Medium", "au restaurant", "at the restaurant"),
  w("Term 4", "In Paris past tense", "Medium", "un beau garçon", "a handsome boy"),
  w("Term 4", "In Paris past tense", "Medium", "une belle fille", "a pretty girl"),
  w("Term 4", "In Paris past tense", "Medium", "des cartes postales (à) …", "postcards (to) …"),
  w("Term 4", "In Paris past tense", "Low", "le feu d'artifice", "fireworks"),
  w("Term 4", "In Paris past tense", "Low", "le défilé", "the parade"),
  w("Term 4", "In Paris past tense", "Medium", "des souvenirs", "some souvenirs"),

  // Term 4 — Irregular past tense
  w("Term 4", "Irregular past tense", "Low", "j'ai vu", "I saw / I have seen"),
  w("Term 4", "Irregular past tense", "Medium", "j'ai bu", "I drank / I have drunk"),
  w("Term 4", "Irregular past tense", "Medium", "j'ai fait", "I did / I have done"),
  w("Term 4", "Irregular past tense", "Medium", "j'ai pris", "I took / I have taken"),
  w("Term 4", "Irregular past tense", "Medium", "j'ai dormi", "I slept"),
  w("Term 4", "Irregular past tense", "High", "j'ai attendu", "I waited"),
  w("Term 4", "Irregular past tense", "Low", "je suis allé", "I went"),
  w("Term 4", "Irregular past tense", "Medium", "une balade", "a ride"),
  w("Term 4", "Irregular past tense", "Medium", "en bateau-mouche", "on a sightseeing boat"),
  w("Term 4", "Irregular past tense", "Medium", "en Segway", "on a Segway"),
  w("Term 4", "Irregular past tense", "Medium", "en vélo", "on a bike"),
  w("Term 4", "Irregular past tense", "Medium", "la Joconde", "the Mona Lisa"),
  w("Term 4", "Irregular past tense", "Medium", "tous les monuments", "all the monuments"),
  w("Term 4", "Irregular past tense", "Medium", "beaucoup de photos", "a lot of photos"),
  w("Term 4", "Irregular past tense", "Medium", "hier", "yesterday"),
  w("Term 4", "Irregular past tense", "Medium", "avant-hier", "the day before yesterday"),

  // Term 4 — Opinions on catacombs
  w("Term 4", "Opinions on catacombs", "Low", "c'était", "it was"),
  w("Term 4", "Opinions on catacombs", "Medium", "ce n'était pas", "it was not"),
  w("Term 4", "Opinions on catacombs", "Medium", "formidable", "amazing"),
  w("Term 4", "Opinions on catacombs", "Medium", "fabuleux", "fabulous"),
  w("Term 4", "Opinions on catacombs", "Medium", "génial", "great"),
  w("Term 4", "Opinions on catacombs", "Medium", "cool", "cool"),
  w("Term 4", "Opinions on catacombs", "Medium", "marrant", "funny"),
  w("Term 4", "Opinions on catacombs", "Medium", "intéressant", "interesting"),
  w("Term 4", "Opinions on catacombs", "Medium", "bizarre", "bizarre/weird"),
  w("Term 4", "Opinions on catacombs", "Medium", "effrayant", "frightening"),
  w("Term 4", "Opinions on catacombs", "Medium", "horrible", "horrible"),
  w("Term 4", "Opinions on catacombs", "Medium", "nul", "rubbish"),
  w("Term 4", "Opinions on catacombs", "Medium", "cher", "expensive"),
  w("Term 4", "Opinions on catacombs", "Medium", "ouvert", "open"),
  w("Term 4", "Opinions on catacombs", "Medium", "fermé", "closed"),
  w("Term 4", "Opinions on catacombs", "Medium", "gratuit", "free"),

  // Term 5 — Holidays
  w("Term 5", "Holidays", "Low", "Où ?", "Where?"),
  w("Term 5", "Holidays", "Low", "Avec qui ?", "Who with?"),
  w("Term 5", "Holidays", "Low", "Combien de temps ?", "How long for?"),
  w(
    "Term 5",
    "Holidays",
    "Medium",
    "Que fais-tu quand tu vas en vacances ?",
    "What do you do when you go on holidays?",
  ),
  w("Term 5", "Holidays", "Medium", "Je fais du canoë-kayak", "I do canoeing"),
  w("Term 5", "Holidays", "Low", "Je fais du VTT", "I do mountain biking"),
  w("Term 5", "Holidays", "Medium", "Je fais du ski", "I do skiing"),
  w("Term 5", "Holidays", "Medium", "Je fais de la voile", "I do sailing"),
  w(
    "Term 5",
    "Holidays",
    "Medium",
    "Où passes-tu tes vacances ?",
    "Where do you spend your holidays?",
  ),
  w("Term 5", "Holidays", "Low", "Je passe mes vacances", "I spend my holidays"),
  w("Term 5", "Holidays", "Low", "au bord de la mer", "at the seaside"),
  w("Term 5", "Holidays", "Low", "à la campagne", "in the countryside"),
  w("Term 5", "Holidays", "Low", "à la montagne", "in the mountains"),
  w("Term 5", "Holidays", "Medium", "en colo", "in a summer camp"),
  w(
    "Term 5",
    "Holidays",
    "Medium",
    "Combien de temps restes-tu en vacances ?",
    "How long do you stay on holidays?",
  ),
  w("Term 5", "Holidays", "Low", "Je reste", "I stay"),
  w("Term 5", "Holidays", "Low", "une semaine", "a week"),
  w("Term 5", "Holidays", "Medium", "quinze jours", "2 weeks (15 days)"),
  w("Term 5", "Holidays", "Medium", "dix jours", "10 days"),

  // Term 5 — Different holidays
  w("Term 5", "Different holidays", "Low", "Un jour, je voudrais …", "One day, I would like …"),
  w("Term 5", "Different holidays", "Low", "aller au pôle nord", "to go to the North Pole"),
  w(
    "Term 5",
    "Different holidays",
    "Low",
    "faire un safari en Afrique",
    "to do a safari in Africa",
  ),
  w("Term 5", "Different holidays", "Low", "faire de la plongée sous-marine", "to do scuba-diving"),
  w("Term 5", "Different holidays", "Low", "faire des sports extrêmes", "to do extreme sports"),
  w("Term 5", "Different holidays", "Low", "faire du camping", "to go camping"),
  w("Term 5", "Different holidays", "Medium", "seul(e)", "alone"),
  w("Term 5", "Different holidays", "Medium", "dans une forêt", "in a forest"),
  w(
    "Term 5",
    "Different holidays",
    "Low",
    "faire de la randonnée dans une jungle",
    "to go hiking in a jungle",
  ),
  w(
    "Term 5",
    "Different holidays",
    "Low",
    "rester sur une île déserte",
    "to stay on a desert island",
  ),
  w("Term 5", "Different holidays", "Low", "nager avec les requins", "to swim with sharks"),
  w("Term 5", "Different holidays", "Low", "manger des insectes", "to eat insects"),
];
