/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GameSettingsRouteImport } from './routes/game-settings'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as GameSettingsIndexRouteImport } from './routes/game-settings.index'
import { Route as GameSettingsImagesRouteImport } from './routes/game-settings.images'
import { Route as GameSettingsWheelRouteImport } from './routes/game-settings.wheel'
import { Route as GameSettingsWheelIndexRouteImport } from './routes/game-settings.wheel.index'
import { Route as GameSettingsWheelLessonRouteImport } from './routes/game-settings.wheel.lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSettingsRoute = GameSettingsRouteImport.update({
  id: '/game-settings',
  path: '/game-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSettingsIndexRoute = GameSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameSettingsRoute,
} as any)
const GameSettingsImagesRoute = GameSettingsImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => GameSettingsRoute,
} as any)
const GameSettingsWheelRoute = GameSettingsWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => GameSettingsRoute,
} as any)
const GameSettingsWheelIndexRoute = GameSettingsWheelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameSettingsWheelRoute,
} as any)
const GameSettingsWheelLessonRoute = GameSettingsWheelLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => GameSettingsWheelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/game-settings': typeof GameSettingsRouteWithChildren
  '/home': typeof HomeRoute
  '/set-password': typeof SetPasswordRoute
  '/vocabulary': typeof VocabularyRoute
  '/wheel': typeof WheelRoute
  '/game-settings/images': typeof GameSettingsImagesRoute
  '/game-settings/wheel': typeof GameSettingsWheelRouteWithChildren
  '/game-settings/': typeof GameSettingsIndexRoute
  '/game-settings/wheel/lesson': typeof GameSettingsWheelLessonRoute
  '/game-settings/wheel/': typeof GameSettingsWheelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/home': typeof HomeRoute
  '/set-password': typeof SetPasswordRoute
  '/vocabulary': typeof VocabularyRoute
  '/wheel': typeof WheelRoute
  '/game-settings/images': typeof GameSettingsImagesRoute
  '/game-settings': typeof GameSettingsIndexRoute
  '/game-settings/wheel/lesson': typeof GameSettingsWheelLessonRoute
  '/game-settings/wheel': typeof GameSettingsWheelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/game-settings': typeof GameSettingsRouteWithChildren
  '/home': typeof HomeRoute
  '/set-password': typeof SetPasswordRoute
  '/vocabulary': typeof VocabularyRoute
  '/wheel': typeof WheelRoute
  '/game-settings/images': typeof GameSettingsImagesRoute
  '/game-settings/wheel': typeof GameSettingsWheelRouteWithChildren
  '/game-settings/': typeof GameSettingsIndexRoute
  '/game-settings/wheel/lesson': typeof GameSettingsWheelLessonRoute
  '/game-settings/wheel/': typeof GameSettingsWheelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/create'
    | '/game-settings'
    | '/home'
    | '/set-password'
    | '/vocabulary'
    | '/wheel'
    | '/game-settings/images'
    | '/game-settings/wheel'
    | '/game-settings/'
    | '/game-settings/wheel/lesson'
    | '/game-settings/wheel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/create'
    | '/home'
    | '/set-password'
    | '/vocabulary'
    | '/wheel'
    | '/game-settings/images'
    | '/game-settings'
    | '/game-settings/wheel/lesson'
    | '/game-settings/wheel'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/create'
    | '/game-settings'
    | '/home'
    | '/set-password'
    | '/vocabulary'
    | '/wheel'
    | '/game-settings/images'
    | '/game-settings/wheel'
    | '/game-settings/'
    | '/game-settings/wheel/lesson'
    | '/game-settings/wheel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CreateRoute: typeof CreateRoute
  GameSettingsRoute: typeof GameSettingsRouteWithChildren
  HomeRoute: typeof HomeRoute
  SetPasswordRoute: typeof SetPasswordRoute
  VocabularyRoute: typeof VocabularyRoute
  WheelRoute: typeof WheelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-settings': {
      id: '/game-settings'
      path: '/game-settings'
      fullPath: '/game-settings'
      preLoaderRoute: typeof GameSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-settings/': {
      id: '/game-settings/'
      path: '/'
      fullPath: '/game-settings/'
      preLoaderRoute: typeof GameSettingsIndexRouteImport
      parentRoute: typeof GameSettingsRoute
    }
    '/game-settings/images': {
      id: '/game-settings/images'
      path: '/images'
      fullPath: '/game-settings/images'
      preLoaderRoute: typeof GameSettingsImagesRouteImport
      parentRoute: typeof GameSettingsRoute
    }
    '/game-settings/wheel': {
      id: '/game-settings/wheel'
      path: '/wheel'
      fullPath: '/game-settings/wheel'
      preLoaderRoute: typeof GameSettingsWheelRouteImport
      parentRoute: typeof GameSettingsRoute
    }
    '/game-settings/wheel/': {
      id: '/game-settings/wheel/'
      path: '/'
      fullPath: '/game-settings/wheel/'
      preLoaderRoute: typeof GameSettingsWheelIndexRouteImport
      parentRoute: typeof GameSettingsWheelRoute
    }
    '/game-settings/wheel/lesson': {
      id: '/game-settings/wheel/lesson'
      path: '/lesson'
      fullPath: '/game-settings/wheel/lesson'
      preLoaderRoute: typeof GameSettingsWheelLessonRouteImport
      parentRoute: typeof GameSettingsWheelRoute
    }
  }
}

interface GameSettingsWheelRouteChildren {
  GameSettingsWheelLessonRoute: typeof GameSettingsWheelLessonRoute
  GameSettingsWheelIndexRoute: typeof GameSettingsWheelIndexRoute
}

const GameSettingsWheelRouteChildren: GameSettingsWheelRouteChildren = {
  GameSettingsWheelLessonRoute: GameSettingsWheelLessonRoute,
  GameSettingsWheelIndexRoute: GameSettingsWheelIndexRoute,
}

const GameSettingsWheelRouteWithChildren =
  GameSettingsWheelRoute._addFileChildren(GameSettingsWheelRouteChildren)

interface GameSettingsRouteChildren {
  GameSettingsImagesRoute: typeof GameSettingsImagesRoute
  GameSettingsWheelRoute: typeof GameSettingsWheelRouteWithChildren
  GameSettingsIndexRoute: typeof GameSettingsIndexRoute
}

const GameSettingsRouteChildren: GameSettingsRouteChildren = {
  GameSettingsImagesRoute: GameSettingsImagesRoute,
  GameSettingsWheelRoute: GameSettingsWheelRouteWithChildren,
  GameSettingsIndexRoute: GameSettingsIndexRoute,
}

const GameSettingsRouteWithChildren = GameSettingsRoute._addFileChildren(
  GameSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CreateRoute: CreateRoute,
  GameSettingsRoute: GameSettingsRouteWithChildren,
  HomeRoute: HomeRoute,
  SetPasswordRoute: SetPasswordRoute,
  VocabularyRoute: VocabularyRoute,
  WheelRoute: WheelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
